spring:
  redis:
    database: 0
    host: 192.168.0.161
    port: 6379
    password:
    timeout: 5000
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    username: techcomeredu
#    password: techcomeredu
#    url: jdbc:p6spy:mysql://192.168.0.161:3306/edu?characterEncoding=utf-8&useSSL=false&&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
