spring:
  profiles:
    active: dev
#  pool:
#    max-active: 200 # 连接池最大连接数（使用负值表示没有限制
#    max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制
#    max-idle: 8      # 连接池中的最大空闲连接
#    min-idle: 0       # 连接池中的最小空闲连接
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    # 服务名称，使用"-"，禁止使用"_"
    name: edu-schedule


server:
  port: 18010

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 最少42位
  secret: 12345678901234567890123456789012
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600